name: gcoord_dart
description: A starting point for Dart libraries or applications.
version: 0.2.3
repository: https://github.com/TonyStark106/gcoord_dart

environment:
  sdk: '>=2.8.1 <3.0.0'

dev_dependencies:
  test: ^1.14.4
  geo: ^0.2.4
  extended_math: ^0.0.29+1
