on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v2
      - run: pub get
      - run: pub run test -r json test/gcoord_dart_test.dart --reporter=expanded
